title: Iago Sousa
email: fciagsousa94@gmail.com
description: Hello, this is my portfolio!
baseurl: ""
url: "iagsousa.github.io"
twitter_username: IagoSousaCC
github_username:  iagsousa

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5

sass:
  sass_dir: assets/css
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
